// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { SupabaseClient } from '@supabase/supabase-js';

// Credenciais fornecidas pelo usuário para o projeto zdbjzrpgliqicwvncfpc
export const SUPABASE_URL = "https://myylkpoisqijfnptlnyk.supabase.co";
// CHAVE PÚBLICA (ANON KEY) - Chave correta para uso no lado do cliente.
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15eWxrcG9pc3FpamZucHRsbnlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MzQxNTIsImV4cCI6MjA3MjAxMDE1Mn0.me7aXILmeIHvjbkYWUVczOZt7gxrz8Rddv515Xa9ZTU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Função helper para criar um mock que falha na verificação
const createMockClient = (): SupabaseClient => {
  return {
    from: () => {
      throw new Error("Supabase client failed to initialize. Please refresh the page.");
    }
  } as unknown as SupabaseClient;
};

// Silenciar logs de leitura/escrita do storage (podem poluir o console)
const STORAGE_DEBUG = (() => {
  try {
    return sessionStorage.getItem('supabase-storage-debug') === 'true';
  } catch {
    return false;
  }
})();
const logStorage = (...args: any[]) => {
  if (STORAGE_DEBUG) {
    // eslint-disable-next-line no-console
    console.log(...args);
  }
};

let client: SupabaseClient;

try {
  // Validação das credenciais antes de criar o cliente
  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    throw new Error("Supabase URL or ANON KEY is missing in environment variables.");
  }

  client = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
    auth: {
      autoRefreshToken: true, // Enable automatic token refresh
      // Persist session in localStorage by default
      persistSession: true,
      // Detect session from URL on redirect
      detectSessionInUrl: true,
      // Storage configuration
      storage: {
        getItem: (key: string) => {
          try {
            // Check if we should use sessionStorage (for non-persistent sessions)
            const useSessionStorage = sessionStorage.getItem('supabase-use-session-storage');
            if (useSessionStorage === 'true') {
              const value = sessionStorage.getItem(key);
              // Log apenas para chaves importantes de auth
              if (key.includes('auth-token') || key.includes('supabase.auth')) logStorage(`🔑 [Supabase Storage] Reading ${key} from sessionStorage:`, value ? 'Found' : 'Not found');
              return value;
            }
            const value = localStorage.getItem(key);
            // Log apenas para chaves importantes de auth
            if (key.includes('auth-token') || key.includes('supabase.auth')) logStorage(`🔑 [Supabase Storage] Reading ${key} from localStorage:`, value ? 'Found' : 'Not found');
            return value;
          } catch (e) {
            console.error('❌ [Supabase Storage] Error reading from storage:', e);
            return null;
          }
        },
        setItem: (key: string, value: string) => {
          try {
            const useSessionStorage = sessionStorage.getItem('supabase-use-session-storage');
            if (useSessionStorage === 'true') {
              sessionStorage.setItem(key, value);
              // Log apenas para chaves importantes de auth
              if (key.includes('auth-token') || key.includes('supabase.auth')) logStorage(`💾 [Supabase Storage] Saved ${key} to sessionStorage`);
            } else {
              localStorage.setItem(key, value);
              // Log apenas para chaves importantes de auth
              if (key.includes('auth-token') || key.includes('supabase.auth')) logStorage(`💾 [Supabase Storage] Saved ${key} to localStorage`);
            }
          } catch (e) {
            console.error('❌ [Supabase Storage] Error writing to storage:', e);
          }
        },
        removeItem: (key: string) => {
          try {
            localStorage.removeItem(key);
            sessionStorage.removeItem(key);
            // Log apenas para chaves importantes de auth
            if (key.includes('auth-token') || key.includes('supabase.auth')) logStorage(`🗑️ [Supabase Storage] Removed ${key} from both storages`);
          } catch (e) {
            console.error('❌ [Supabase Storage] Error removing from storage:', e);
          }
        },
      }
    }
  });

  // Verificação crítica: garantir que o cliente foi criado corretamente
  if (!client || typeof client.from !== 'function') {
    console.error("Supabase client created but 'from' method is missing.");
    client = createMockClient();
  }
} catch (e) {
  console.error("Failed to initialize Supabase client:", e);
  // Em caso de falha crítica, definimos um objeto mock para evitar 'undefined'
  client = createMockClient();
}

// Garantir que sempre exportamos um cliente válido
export const supabase = client;

// Log de debug detalhado com parte da chave (seguro em dev)
if (typeof window !== 'undefined') {
  if (STORAGE_DEBUG) {
    console.log('[Supabase Client] Initialized:', {
      hasClient: !!client,
      hasFromMethod: typeof client?.from === 'function',
      url: SUPABASE_URL,
      keyStart: SUPABASE_ANON_KEY ? SUPABASE_ANON_KEY.substring(0, 10) + '...' : 'MISSING',
      isDev: (import.meta as any)?.env?.DEV
    });
  }
}
