// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { SupabaseClient } from '@supabase/supabase-js';

// Credenciais fornecidas pelo usuário para o projeto zdbjzrpgliqicwvncfpc
const SUPABASE_URL = "https://zdbjzrpgliqicwvncfpc.supabase.co";
// CHAVE PÚBLICA (ANON KEY) - Chave correta para uso no lado do cliente.
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkYmp6cnBnbGlxaWN3dm5jZnBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2ODI3MzUsImV4cCI6MjA3MzI1ODczNX0.VOrT3YAVhCqkbSmV-POeb4sVTgmu756sivqT1_9vCr4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

let client: SupabaseClient | undefined;

try {
  client = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
    auth: {
      // Enable automatic token refresh
      autoRefreshToken: true,
      // Persist session in localStorage by default
      persistSession: true,
      // Detect session from URL on redirect
      detectSessionInUrl: true,
      // Storage configuration
      storage: {
        getItem: (key: string) => {
          // Check if we should use sessionStorage (for non-persistent sessions)
          const useSessionStorage = sessionStorage.getItem('supabase-use-session-storage');
          if (useSessionStorage === 'true') {
            return sessionStorage.getItem(key);
          }
          return localStorage.getItem(key);
        },
        setItem: (key: string, value: string) => {
          const useSessionStorage = sessionStorage.getItem('supabase-use-session-storage');
          if (useSessionStorage === 'true') {
            sessionStorage.setItem(key, value);
          } else {
            localStorage.setItem(key, value);
          }
        },
        removeItem: (key: string) => {
          localStorage.removeItem(key);
          sessionStorage.removeItem(key);
        },
      }
    }
  });
} catch (e) {
  console.error("Failed to initialize Supabase client:", e);
  // Em caso de falha crítica, definimos um objeto mock para evitar 'undefined'
  // e garantir que a verificação 'typeof supabase.from' falhe corretamente nos hooks.
  client = { from: () => { throw new Error("Supabase client failed to initialize."); } } as unknown as SupabaseClient;
}

export const supabase = client as SupabaseClient;