// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://pxyrvddyyeqhxudhdcoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4eXJ2ZGR5eWVxaHh1ZGhkY29qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MDMzNTQsImV4cCI6MjA3NDQ3OTM1NH0.DdiP2M5V2v3RLcjmWa8Yck4kzBsLsVvmN1k9EuHX190";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Enable automatic token refresh
    autoRefreshToken: true,
    // Persist session in localStorage by default
    persistSession: true,
    // Detect session from URL on redirect
    detectSessionInUrl: true,
    // Storage configuration
    storage: {
      getItem: (key: string) => {
        // Check if we should use sessionStorage (for non-persistent sessions)
        const useSessionStorage = sessionStorage.getItem('supabase-use-session-storage');
        if (useSessionStorage === 'true') {
          return sessionStorage.getItem(key);
        }
        return localStorage.getItem(key);
      },
      setItem: (key: string, value: string) => {
        const useSessionStorage = sessionStorage.getItem('supabase-use-session-storage');
        if (useSessionStorage === 'true') {
          sessionStorage.setItem(key, value);
        } else {
          localStorage.setItem(key, value);
        }
      },
      removeItem: (key: string) => {
        localStorage.removeItem(key);
        sessionStorage.removeItem(key);
      },
    }
  }
});